# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c30928a826ca8c7d3f04718cf48617ac847622036fb1d0afa77baf37aefa9468d5e5db061e5dac20809219f9a7f231eec3edb22cda0a993264b51d565d9b5899

test:
  secret_key_base: bf170cc08babb7a33c0a6690fb1e55b04df6878188835a345f35f734592b35519a98df89c4dae0ca10aaaec0010e703a00260152e4028f18aba97ba0e14f801c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
